export enum TaskStatus {
    STATUS_PENDING = 'STATUS_PENDING',
    STATUS_PENDING_AUTOCOMPLETE = 'STATUS_PENDING_AUTOCOMPLETE',
    STATUS_ACTIVE = 'STATUS_ACTIVE',
    STATUS_ACTIVE_AUTOCOMPLETE = 'STATUS_ACTIVE_AUTOCOMPLETE',
    STATUS_COMPLETED = 'STATUS_COMPLETED',
    STATUS_OVERDUE = 'STATUS_OVERDUE'
}
